import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import {
  ArrowRight, BarChart3, Bell, CalendarClock, Camera, Check, Clock3, Edit3, Image as ImageIcon,
  Landmark, LockKeyhole, LogIn, MapPin, Menu, PackageSearch, Pencil, Search, Send, ShieldCheck,
  Sparkles, Trash2, Upload, UserRound, UsersRound, X, Zap,
} from 'lucide-react';
import { supabase } from '@/lib/supabase';

type ReportType = 'lost' | 'found';
type ReportStatus = 'active' | 'matched' | 'returned';
type Language = 'th' | 'en';
type Report = { id: string; user_id?: string | null; type: ReportType; title: string; description: string; category: string; location: string; image_url: string | null; status: ReportStatus; created_at: string };
type AuthMode = 'login' | 'signup';
type ReportForm = { type: ReportType; title: string; description: string; category: string; location: string; image_url: string };
type ReturnForm = { meeting_location: string; meeting_time: string; verification_note: string; message: string };

const photoUrls = {
  backpack: 'https://images.pexels.com/photos/7869720/pexels-photo-7869720.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  earbuds: 'https://images.pexels.com/photos/5099869/pexels-photo-5099869.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  wallet: 'https://images.pexels.com/photos/9053308/pexels-photo-9053308.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  phone: 'https://images.pexels.com/photos/14541095/pexels-photo-14541095.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
};
const demoReports: Report[] = [
  { id: 'demo-backpack', type: 'lost', title: 'Black Backpack', description: 'Black everyday backpack with a small keychain.', category: 'Bags', location: 'Engineering Building', image_url: photoUrls.backpack, status: 'active', created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
  { id: 'demo-airpods', type: 'found', title: 'AirPods Case', description: 'White AirPods case found near the library entrance.', category: 'Electronics', location: 'Library', image_url: photoUrls.earbuds, status: 'active', created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() },
  { id: 'demo-wallet', type: 'lost', title: 'Pink Wallet', description: 'Small pink wallet with cards inside.', category: 'Accessories', location: 'Cafeteria', image_url: photoUrls.wallet, status: 'active', created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString() },
  { id: 'demo-phone', type: 'found', title: 'iPhone 13', description: 'Dark blue iPhone found near the main gate.', category: 'Electronics', location: 'Main Gate', image_url: photoUrls.phone, status: 'active', created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString() },
];
const emptyForm: ReportForm = { type: 'lost', title: '', description: '', category: 'Electronics', location: '', image_url: '' };
const emptyReturn: ReturnForm = { meeting_location: '', meeting_time: '', verification_note: '', message: '' };
const categories = ['Electronics', 'Bags', 'Accessories', 'Documents', 'Keys', 'Other'];
const copy = {
  th: { home: 'หน้าแรก', lost: 'แจ้งของหาย', found: 'แจ้งของที่พบ', browse: 'ค้นหาของหาย', about: 'เกี่ยวกับเรา', login: 'เข้าสู่ระบบ / สมัครสมาชิก', signout: 'ออกจากระบบ', heroTag: 'ช่วยกันตามหาของสำคัญ', heroTitle: 'ของหายใช่ไหม?\nเราจะช่วยตามหา', heroText: 'ศูนย์กลาง Lost & Found สำหรับชาว KMITL ค้นหาจากชื่อ รายละเอียด และรูปภาพ พร้อมติดต่อคืนของอย่างปลอดภัย', search: 'ค้นหาของที่หาย เช่น กระเป๋า โทรศัพท์ กระเป๋าสตางค์', searchButton: 'ค้นหา', recent: 'รายการล่าสุด', community: 'พื้นที่ช่วยเหลือของชุมชน', all: 'ทั้งหมด', lostShort: 'ของหาย', foundShort: 'ของที่พบ', reportTitle: 'แจ้งของหายหรือของที่พบ', reportText: 'เพิ่มรายละเอียดหรือรูปภาพ แล้วให้ระบบช่วยแนะนำรายการที่อาจตรงกัน', upload: 'เพิ่มรายการใหม่', quick: 'สถิติการใช้งาน', myItems: 'รายการของฉัน', smart: 'Smart Match', contact: 'ติดต่อขอคืนของ', edit: 'แก้ไข', delete: 'ลบรายการ', noItems: 'ยังไม่พบรายการที่ตรงกัน', accountRequired: 'กรุณาเข้าสู่ระบบก่อนดำเนินการ', saved: 'บันทึกข้อมูลเรียบร้อยแล้ว' },
  en: { home: 'Home', lost: 'Report Lost', found: 'Report Found', browse: 'Find an Item', about: 'About', login: 'Login / Sign Up', signout: 'Sign out', heroTag: 'Find what matters', heroTitle: 'Lost something?\nWe are here to help', heroText: 'A KMITL community hub to search by name, details, and images, then arrange a safe return.', search: 'Search for an item e.g. wallet, phone, bag', searchButton: 'Search', recent: 'Recent Lost & Found', community: 'Community board', all: 'All', lostShort: 'Lost', foundShort: 'Found', reportTitle: 'Report a lost or found item', reportText: 'Add details or a photo and get suggested matches.', upload: 'Add new item', quick: 'Quick stats', myItems: 'My reports', smart: 'Smart Match', contact: 'Request a safe return', edit: 'Edit', delete: 'Delete report', noItems: 'No matching items yet', accountRequired: 'Please sign in first', saved: 'Saved successfully' },
};
function formatTime(dateString: string, language: Language): string { const hours = Math.max(1, Math.round((Date.now() - new Date(dateString).getTime()) / 3600000)); if (hours < 24) return language === 'th' ? `${hours} ชั่วโมงที่แล้ว` : `${hours} hour${hours === 1 ? '' : 's'} ago`; const days = Math.round(hours / 24); return language === 'th' ? `${days} วันที่แล้ว` : `${days} day${days === 1 ? '' : 's'} ago`; }
function scoreMatch(report: Report, form: ReportForm): number { const source = `${form.title} ${form.description} ${form.category} ${form.location}`.toLowerCase(); const target = `${report.title} ${report.description} ${report.category} ${report.location}`.toLowerCase(); const words = source.split(/\s+/).filter((word) => word.length > 2); return words.reduce((score, word) => score + (target.includes(word) ? 1 : 0), 0) + (report.type !== form.type ? 1 : 0); }

function App() {
  const [language, setLanguage] = useState<Language>('th');
  const text = copy[language];
  const [reports, setReports] = useState<Report[]>(demoReports);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | ReportType>('all');
  const [authMode, setAuthMode] = useState<AuthMode | null>(null);
  const [reportOpen, setReportOpen] = useState(false);
  const [form, setForm] = useState<ReportForm>(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [authEmail, setAuthEmail] = useState('');
  const [authPassword, setAuthPassword] = useState('');
  const [userEmail, setUserEmail] = useState<string | null>(null);
  const [userId, setUserId] = useState<string | null>(null);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [myReportsOpen, setMyReportsOpen] = useState(false);
  const [detailReport, setDetailReport] = useState<Report | null>(null);
  const [returnReport, setReturnReport] = useState<Report | null>(null);
  const [returnForm, setReturnForm] = useState<ReturnForm>(emptyReturn);
  const [imagePreview, setImagePreview] = useState<string | null>(null);

  useEffect(() => { void loadReports(); void supabase.auth.getSession().then(({ data }) => { setUserEmail(data.session?.user.email ?? null); setUserId(data.session?.user.id ?? null); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { setUserEmail(session?.user.email ?? null); setUserId(session?.user.id ?? null); }); return () => listener.subscription.unsubscribe(); }, []);
  async function loadReports(): Promise<void> { const { data, error } = await supabase.from('lost_found_reports').select('id,user_id,type,title,description,category,location,image_url,status,created_at').order('created_at', { ascending: false }); if (!error && data && data.length > 0) setReports(data as Report[]); }
  const filteredReports = useMemo(() => { const normalized = query.trim().toLowerCase(); return reports.filter((report) => (filter === 'all' || report.type === filter) && (!normalized || `${report.title} ${report.description} ${report.category} ${report.location}`.toLowerCase().includes(normalized))); }, [filter, query, reports]);
  const mine = useMemo(() => reports.filter((report) => userId && report.user_id === userId), [reports, userId]);
  const suggestions = useMemo(() => reports.filter((report) => !report.id.startsWith('demo-') || form.title || form.description).filter((report) => scoreMatch(report, form) > 0).sort((a, b) => scoreMatch(b, form) - scoreMatch(a, form)).slice(0, 3), [form, reports]);
  const stats = useMemo(() => ({ total: reports.length, found: reports.filter((report) => report.type === 'found').length, missing: reports.filter((report) => report.type === 'lost' && report.status === 'active').length, matched: reports.filter((report) => report.status !== 'active').length }), [reports]);
  function openReport(type: ReportType, report?: Report): void { setEditingId(report?.id ?? null); setForm(report ? { type: report.type, title: report.title, description: report.description, category: report.category, location: report.location, image_url: report.image_url ?? '' } : { ...emptyForm, type }); setImagePreview(report?.image_url ?? null); setReportOpen(true); }
  function requireAccount(action: () => void): void { if (!userId) { setAuthMode('login'); setMessage(text.accountRequired); return; } action(); }
  async function submitAuth(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); setBusy(true); setMessage(''); const result = authMode === 'login' ? await supabase.auth.signInWithPassword({ email: authEmail, password: authPassword }) : await supabase.auth.signUp({ email: authEmail, password: authPassword }); setBusy(false); if (result.error) { setMessage(language === 'th' ? 'อีเมลหรือรหัสผ่านไม่ถูกต้อง กรุณาลองใหม่' : 'Email or password is incorrect.'); return; } setAuthMode(null); setAuthEmail(''); setAuthPassword(''); setMessage(language === 'th' ? 'เข้าสู่ระบบสำเร็จ' : 'Welcome back.'); }
  async function signOut(): Promise<void> { await supabase.auth.signOut(); setMessage(language === 'th' ? 'ออกจากระบบแล้ว' : 'You have been signed out.'); }
  async function submitReport(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!userId) { setReportOpen(false); setAuthMode('login'); setMessage(text.accountRequired); return; } setBusy(true); const result = editingId ? await supabase.from('lost_found_reports').update(form).eq('id', editingId).eq('user_id', userId).select('id,user_id,type,title,description,category,location,image_url,status,created_at').maybeSingle() : await supabase.from('lost_found_reports').insert(form).select('id,user_id,type,title,description,category,location,image_url,status,created_at').maybeSingle(); setBusy(false); if (result.error || !result.data) { setMessage(language === 'th' ? 'บันทึกไม่สำเร็จ กรุณาตรวจสอบข้อมูลอีกครั้ง' : 'Could not save this report.'); return; } setReports((current) => editingId ? current.map((report) => report.id === editingId ? result.data as Report : report) : [result.data as Report, ...current.filter((report) => !report.id.startsWith('demo-'))]); setReportOpen(false); setEditingId(null); setForm(emptyForm); setMessage(text.saved); }
  async function deleteReport(report: Report): Promise<void> { if (!userId) return; const { error } = await supabase.from('lost_found_reports').delete().eq('id', report.id).eq('user_id', userId); if (error) { setMessage(language === 'th' ? 'ลบรายการไม่สำเร็จ' : 'Could not delete this report.'); return; } setReports((current) => current.filter((item) => item.id !== report.id)); setMessage(language === 'th' ? 'ลบรายการแล้ว' : 'Report deleted.'); }
  async function submitReturn(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!userId || !returnReport) return; setBusy(true); const { error } = await supabase.from('lost_found_return_requests').insert({ report_id: returnReport.id, ...returnForm }); setBusy(false); if (error) { setMessage(language === 'th' ? 'ส่งคำขอไม่สำเร็จ กรุณาลองใหม่' : 'Could not send the return request.'); return; } setReturnReport(null); setReturnForm(emptyReturn); setMessage(language === 'th' ? 'ส่งคำขอคืนของแล้ว ผู้แจ้งจะติดต่อกลับอย่างปลอดภัย' : 'Return request sent safely.'); }

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#home"><span className="brand-mark"><ShieldCheck size={21} /></span><span>Lost &amp; Found <small>KMITL</small></span></a><button className="mobile-menu" onClick={() => setMobileNav((open) => !open)} aria-label="menu"><Menu size={20} /></button><nav className={mobileNav ? 'main-nav is-open' : 'main-nav'}><a className="active" href="#home">{text.home}</a><button onClick={() => { openReport('lost'); setMobileNav(false); }}>{text.lost}</button><button onClick={() => { openReport('found'); setMobileNav(false); }}>{text.found}</button><a href="#recent">{text.browse}</a><a href="#about">{text.about}</a></nav><div className="top-actions"><div className="language-switch"><button className={language === 'th' ? 'selected' : ''} onClick={() => setLanguage('th')}>TH</button><span>/</span><button className={language === 'en' ? 'selected' : ''} onClick={() => setLanguage('en')}>EN</button></div>{userEmail && <button className="my-items-button" onClick={() => setMyReportsOpen(true)}><Edit3 size={15} /> {text.myItems}</button>}{userEmail ? <button className="account-button" onClick={() => void signOut()}><UserRound size={16} /> {text.signout}</button> : <button className="account-button" onClick={() => setAuthMode('login')}><LogIn size={16} /> {text.login}</button>}</div></header>
    <main><section className="hero" id="home"><div className="hero-copy"><span className="eyebrow"><Sparkles size={14} /> {text.heroTag}</span><h1>{text.heroTitle.split('\n').map((line, index) => <span key={line} className={index === 1 ? 'hero-line-accent' : ''}>{line}{index === 0 && <br />}</span>)}</h1><p>{text.heroText}</p><form className="search-box" onSubmit={(event) => { event.preventDefault(); document.getElementById('recent')?.scrollIntoView({ behavior: 'smooth' }); }}><Search size={19} /><input id="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={text.search} /><button type="submit">{text.searchButton} <ArrowRight size={16} /></button></form></div><div className="hero-visual"><div className="visual-glow" /><div className="visual-note">AI <span>Smart Match</span><br />find your stuff.</div><div className="item-spot backpack-spot"><span>backpack</span><div className="backpack-shape" /></div><div className="item-spot phone-spot"><span>phone</span><div className="phone-shape" /></div><div className="item-spot bottle-spot"><span>bottle</span><div className="bottle-shape" /></div><div className="item-spot earbuds-spot"><span>earbuds</span><div className="earbuds-shape" /></div></div></section>
      <section className="benefits"><Benefit icon={<Sparkles />} tone="orange" title="AI Smart Match" copy={language === 'th' ? 'แนะนำรายการที่อาจตรงกันจากรายละเอียด' : 'Get suggested matches from your details.'} /><Benefit icon={<ShieldCheck />} tone="brown" title={language === 'th' ? 'คืนของอย่างปลอดภัย' : 'Safe handoff'} copy={language === 'th' ? 'นัดหมายในพื้นที่สาธารณะพร้อมข้อมูลยืนยัน' : 'Meet safely with verification details.'} /><Benefit icon={<UsersRound />} tone="cream" title={language === 'th' ? 'ชุมชน KMITL' : 'KMITL community'} copy={language === 'th' ? 'ช่วยกันส่งต่อของกลับคืนเจ้าของ' : 'Help return items to their owners.'} /><Benefit icon={<Zap />} tone="black" title={language === 'th' ? 'รวดเร็วและง่าย' : 'Fast & easy'} copy={language === 'th' ? 'แจ้งรายการได้ในไม่กี่ขั้นตอน' : 'Report in just a few steps.'} /></section>
      <section className="content-grid" id="recent"><div className="recent-panel"><div className="section-heading"><div><p className="kicker">{text.community}</p><h2>{text.recent}</h2></div><button className="view-all" onClick={() => { setQuery(''); setFilter('all'); }}>{text.all} <ArrowRight size={15} /></button></div><div className="filter-row"><button className={filter === 'all' ? 'filter active' : 'filter'} onClick={() => setFilter('all')}>{text.all}</button><button className={filter === 'lost' ? 'filter active' : 'filter'} onClick={() => setFilter('lost')}>{text.lostShort}</button><button className={filter === 'found' ? 'filter active' : 'filter'} onClick={() => setFilter('found')}>{text.foundShort}</button></div>{filteredReports.length > 0 ? <div className="report-grid">{filteredReports.slice(0, 8).map((report) => <ReportCard key={report.id} report={report} language={language} onOpen={() => setDetailReport(report)} />)}</div> : <div className="empty-state"><PackageSearch size={30} /><strong>{text.noItems}</strong><span>{language === 'th' ? 'ลองค้นหาด้วยคำอื่น หรือแจ้งรายการใหม่' : 'Try another search or report it yourself.'}</span></div>}</div><aside className="side-column"><div className="report-cta"><div className="cta-icon"><Camera size={22} /></div><h3>{text.reportTitle}</h3><p>{text.reportText}</p><button onClick={() => requireAccount(() => openReport('lost'))}><Upload size={16} /> {text.upload}</button></div><div className="stats-card"><div className="stats-title"><BarChart3 size={17} /> {text.quick}</div><div className="stats-grid"><Stat icon={<ImageIcon />} value={stats.total} label={language === 'th' ? 'รายการทั้งหมด' : 'Total reports'} tone="orange" /><Stat icon={<Check />} value={stats.found} label={language === 'th' ? 'พบของแล้ว' : 'Items found'} tone="green" /><Stat icon={<Bell />} value={stats.missing} label={language === 'th' ? 'ยังตามหา' : 'Still missing'} tone="red" /><Stat icon={<UsersRound />} value={stats.matched} label={language === 'th' ? 'จับคู่สำเร็จ' : 'Matches'} tone="brown" /></div></div></aside></section><section className="about-strip" id="about"><div className="about-icon"><Landmark size={21} /></div><div><p className="kicker">KMITL Lost &amp; Found</p><h2>{language === 'th' ? 'ของชิ้นเล็กก็มีความหมาย มาช่วยกันส่งคืน' : 'Small things matter. Let’s get them back.'}</h2></div><p>{language === 'th' ? 'ค้นหา ติดต่อ และนัดหมายคืนของด้วยความใส่ใจ' : 'Search, connect, and arrange a safe return.'}</p></section></main>
    <footer><div className="brand footer-brand"><span className="brand-mark"><ShieldCheck size={18} /></span><span>Lost &amp; Found</span></div><span>KMITL community</span><div className="footer-links"><a href="#about">Terms</a><a href="#about">Privacy</a><a href="mailto:hello@lostfound.kmitl.ac.th">Contact</a></div></footer>
    {message && <div className="toast"><Check size={16} /> {message}<button onClick={() => setMessage('')} aria-label="Dismiss"><X size={15} /></button></div>}
    {authMode && <Modal title={authMode === 'login' ? (language === 'th' ? 'เข้าสู่ระบบ' : 'Welcome back') : (language === 'th' ? 'สมัครสมาชิก KMITL' : 'Join the KMITL community')} onClose={() => setAuthMode(null)}><form className="modal-form" onSubmit={submitAuth}><p>{language === 'th' ? 'เข้าสู่ระบบเพื่อแจ้ง ติดตาม และติดต่อคืนของ' : 'Sign in to report, track, and arrange returns.'}</p><label>{language === 'th' ? 'อีเมล' : 'Email'}<input type="email" required value={authEmail} onChange={(event) => setAuthEmail(event.target.value)} placeholder="you@kmitl.ac.th" /></label><label>{language === 'th' ? 'รหัสผ่าน' : 'Password'}<input type="password" required minLength={6} value={authPassword} onChange={(event) => setAuthPassword(event.target.value)} placeholder={language === 'th' ? 'อย่างน้อย 6 ตัวอักษร' : 'At least 6 characters'} /></label><button className="primary-button" disabled={busy}>{busy ? '...' : authMode === 'login' ? (language === 'th' ? 'เข้าสู่ระบบ' : 'Sign in') : (language === 'th' ? 'สร้างบัญชี' : 'Create account')}</button><button type="button" className="switch-button" onClick={() => setAuthMode(authMode === 'login' ? 'signup' : 'login')}>{authMode === 'login' ? (language === 'th' ? 'ยังไม่มีบัญชี? สมัครสมาชิก' : 'New here? Create an account') : (language === 'th' ? 'มีบัญชีแล้ว? เข้าสู่ระบบ' : 'Already have an account? Sign in')}</button></form></Modal>}
    {reportOpen && <Modal title={editingId ? text.edit : (form.type === 'lost' ? text.lost : text.found)} onClose={() => setReportOpen(false)}><form className="modal-form" onSubmit={submitReport}><div className="segmented"><button type="button" className={form.type === 'lost' ? 'selected' : ''} onClick={() => setForm({ ...form, type: 'lost' })}>{text.lost}</button><button type="button" className={form.type === 'found' ? 'selected' : ''} onClick={() => setForm({ ...form, type: 'found' })}>{text.found}</button></div><label>{language === 'th' ? 'ชื่อสิ่งของ' : 'Item name'}<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder={language === 'th' ? 'เช่น กระเป๋าเป้สีดำ' : 'e.g. Black backpack'} /></label><div className="form-row"><label>{language === 'th' ? 'หมวดหมู่' : 'Category'}<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>{language === 'th' ? 'สถานที่' : 'Location'}<input required value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} placeholder={language === 'th' ? 'เช่น อาคารวิศวกรรม' : 'e.g. Library'} /></label></div><label>{language === 'th' ? 'รายละเอียด' : 'Details'}<textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder={language === 'th' ? 'สี ตำหนิ หรือรายละเอียดที่ช่วยยืนยัน' : 'Colors, marks, or identifying details'} rows={3} /></label><label>{language === 'th' ? 'อัปโหลดรูป' : 'Upload a photo'}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) setImagePreview(URL.createObjectURL(file)); }} />{imagePreview && <img className="upload-preview" src={imagePreview} alt="preview" />}</label><label>{language === 'th' ? 'ลิงก์รูปภาพ' : 'Photo URL'} <span className="optional">optional</span><input type="url" value={form.image_url} onChange={(event) => { setForm({ ...form, image_url: event.target.value }); setImagePreview(event.target.value || null); }} placeholder="https://..." /></label>{suggestions.length > 0 && <div className="match-preview"><div><Sparkles size={15} /> {text.smart}</div><span>{language === 'th' ? 'พบรายการที่อาจตรงกันจากข้อมูลที่กรอก' : 'Potential matches from your details'}</span>{suggestions.map((suggestion) => <button type="button" key={suggestion.id} onClick={() => setDetailReport(suggestion)}><strong>{suggestion.title}</strong><small>{suggestion.location}</small><ArrowRight size={14} /></button>)}</div>}<button className="primary-button" disabled={busy}><Send size={16} /> {busy ? '...' : editingId ? (language === 'th' ? 'บันทึกการแก้ไข' : 'Save changes') : (language === 'th' ? 'เผยแพร่รายการ' : 'Publish report')}</button></form></Modal>}
    {myReportsOpen && <Modal title={text.myItems} onClose={() => setMyReportsOpen(false)}><div className="my-reports">{mine.length === 0 ? <div className="empty-state"><PackageSearch size={25} /><strong>{language === 'th' ? 'ยังไม่มีรายการของคุณ' : 'No reports yet'}</strong></div> : mine.map((report) => <div className="my-report-row" key={report.id}><div><strong>{report.title}</strong><span>{report.type === 'lost' ? text.lostShort : text.foundShort} · {report.location}</span></div><button onClick={() => { setMyReportsOpen(false); openReport(report.type, report); }} aria-label={text.edit}><Pencil size={15} /></button><button onClick={() => void deleteReport(report)} aria-label={text.delete}><Trash2 size={15} /></button></div>)}</div></Modal>}
    {detailReport && <Modal title={detailReport.title} onClose={() => setDetailReport(null)}><div className="detail-view">{detailReport.image_url && <img src={detailReport.image_url} alt={detailReport.title} />}<div className="detail-meta"><span className={`status ${detailReport.type}`}>{detailReport.type === 'lost' ? text.lostShort : text.foundShort}</span><span><MapPin size={14} /> {detailReport.location}</span><span><Clock3 size={14} /> {formatTime(detailReport.created_at, language)}</span></div><p>{detailReport.description}</p>{detailReport.type === 'found' && detailReport.user_id !== userId && <button className="primary-button" onClick={() => requireAccount(() => { setDetailReport(null); setReturnReport(detailReport); })}><CalendarClock size={16} /> {text.contact}</button>}</div></Modal>}
    {returnReport && <Modal title={text.contact} onClose={() => setReturnReport(null)}><form className="modal-form" onSubmit={submitReturn}><p>{language === 'th' ? 'ข้อมูลนี้จะเห็นเฉพาะผู้เกี่ยวข้องกับรายการ เพื่อการคืนของอย่างปลอดภัย' : 'Only the people involved in this report can see these handoff details.'}</p><label>{language === 'th' ? 'สถานที่นัดหมายสาธารณะ' : 'Public meeting place'}<input required value={returnForm.meeting_location} onChange={(event) => setReturnForm({ ...returnForm, meeting_location: event.target.value })} placeholder={language === 'th' ? 'เช่น ล็อบบี้อาคารเรียนรวม' : 'e.g. Main library lobby'} /></label><label>{language === 'th' ? 'วันและเวลาที่สะดวก' : 'Preferred date and time'}<input required type="datetime-local" value={returnForm.meeting_time} onChange={(event) => setReturnForm({ ...returnForm, meeting_time: event.target.value })} /></label><label>{language === 'th' ? 'ข้อมูลยืนยันความเป็นเจ้าของ' : 'Ownership verification'}<textarea required rows={3} value={returnForm.verification_note} onChange={(event) => setReturnForm({ ...returnForm, verification_note: event.target.value })} placeholder={language === 'th' ? 'บอกลักษณะเฉพาะที่ไม่ได้เปิดเผยในโพสต์' : 'Share a unique detail not shown in the post'} /></label><label>{language === 'th' ? 'ข้อความถึงผู้พบของ' : 'Message'}<textarea rows={2} value={returnForm.message} onChange={(event) => setReturnForm({ ...returnForm, message: event.target.value })} /></label><button className="primary-button" disabled={busy}><Send size={16} /> {language === 'th' ? 'ส่งคำขออย่างปลอดภัย' : 'Send safely'}</button></form></Modal>}
  </div>;
}
function Benefit({ icon, title, copy, tone }: { icon: ReactNode; title: string; copy: string; tone: string }) { return <div className="benefit"><div className={`benefit-icon ${tone}`}>{icon}</div><div><h3>{title}</h3><p>{copy}</p></div></div>; }
function Stat({ icon, value, label, tone }: { icon: ReactNode; value: number; label: string; tone: string }) { return <div className="stat"><div className={`stat-icon ${tone}`}>{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>; }
function ReportCard({ report, language, onOpen }: { report: Report; language: Language; onOpen: () => void }) { return <article className="report-card" onClick={onOpen} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter') onOpen(); }}><div className="card-image">{report.image_url ? <img src={report.image_url} alt={report.title} /> : <div className="image-placeholder"><ImageIcon size={29} /></div>}<span className={`status ${report.type}`}>{report.type === 'lost' ? (language === 'th' ? 'ของหาย' : 'Lost') : (language === 'th' ? 'พบของ' : 'Found')}</span></div><div className="card-body"><h3>{report.title}</h3><p className="location"><MapPin size={14} /> {report.location}</p><p className="time"><Clock3 size={14} /> {formatTime(report.created_at, language)}</p><button aria-label="open"><ArrowRight size={16} /></button></div></article>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><button className="modal-close" onClick={onClose} aria-label="Close"><X size={19} /></button><div className="modal-heading"><div className="modal-heading-icon"><LockKeyhole size={19} /></div><h2>{title}</h2></div>{children}</div></div>; }
export default App;
